language: cpp
os: linux
sudo: required
dist: trusty

branches:
    only:
      - master

git:
    depth: 1

before_install:
  - sudo apt-get -qq --yes update
   
install: 
  - sudo apt-get install --yes libboost-all-dev

before_script:
  - export PARENT_DIR=$TRAVIS_BUILD_DIR/../
  # cmake
  - cd $PARENT_DIR
  - git clone https://github.com/Kitware/CMake.git
  - cd CMake
  - git checkout tags/v3.8.0 -b v380
  - ./bootstrap
  - make && sudo make install
  - cmake --version
  # z3
  - cd $PARENT_DIR
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout tags/z3-4.7.1 -b v471
  - python scripts/mk_make.py
  - cd build
  - make && sudo make install
  - z3 --version

script:
  - cd $TRAVIS_BUILD_DIR/
  # Boost bjam
  - bjam
  - rm -r bin/*
  # CMake
  - mkdir -p $TRAVIS_BUILD_DIR/cbuild && cd cbuild
  - cmake .. 
  - make

notifications:
    email: false
