branches:
  only:
    - master
    - travis

language: cpp

matrix:
  include:
    - name: "linux"
      os: linux
      dist: xenial
      compiler: gcc

    - name: "osx"
      os: osx
      compiler: clang

sudo: required

git:
    depth: 1

addons:
  apt:
    update: true
    packages:
      - libboost-all-dev

  homebrew:
    update: true
    packages:
      - boost
      - boost-python
   
before_install:
  - cmake --version

install: 
  - cd $TRAVIS_BUILD_DIR/../
  # z3
  - git clone https://github.com/Z3Prover/z3.git
  - cd z3
  - git checkout tags/z3-4.7.1 -b v471
  - if [[ "$TRAVIS_COMPILER" == "gcc" ]]; then python scripts/mk_make.py ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH ; fi
  - if [[ "$TRAVIS_COMPILER" == "clang" ]]; then CXX=clang++ CC=clang python scripts/mk_make.py ; fi
  - cd build
  - make && sudo make install
  - z3 --version

before_script:
  - cmake --version

script:
  - cd $TRAVIS_BUILD_DIR/
  # CMake
  - mkdir -p $TRAVIS_BUILD_DIR/cbuild && cd cbuild
  - cmake .. 
  - make
  # Boost bjam
  - cd $TRAVIS_BUILD_DIR
  - bjam
  

notifications:
    email: false

